name: Test Action Dispatch
on:
  repository_dispatch:
    types: [test_dispatch]
jobs:
  test-dispatch:
    name: Test Dispatched Import Action
    runs-on: ubuntu-latest
    steps:
      - name: Mask SSH Inputs from Log
        run: |
          SSH_KEY_INPUT_SECRET=$(jq -r '.client_payload["ssh-key"]' $GITHUB_EVENT_PATH )
          echo "::add-mask::$SSH_KEY_INPUT_SECRET"
      - uses: RubenBal/import-from-git@v1
        with:
          git-url: ${{ github.event.client_payload.git-url }}
          branch: ${{ github.event.client_payload.branch }}
          output-dir: ${{ github.event.client_payload.output-dir }}
          input-dir: ${{ github.event.client_payload.input-dir }}
          ssh-key: ${{ github.event.client_payload.ssh-key }}
          ssh-known-hosts: ${{ github.event.client_payload.ssh-known-hosts }}